[package]
name = "ruby_rust_sndbox"
version = "0.1.0"
edition = "2021"
authors = ["Aleksandr Gavrishchuk <alex.phyp@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
